name: gldas
channels:
  - conda-forge
  - defaults
dependencies:
- pandas
- numpy
- pygrib
- netcdf4
- pyresample
- pip
- pip:
    - pygeobase
    - pynetcf
    - repurpose
    - datedown>=0.3
    - trollsift
    - pytest-cov
    - coverage
    - pytest
